from iterpy import Arr

from pydantic_codegen.ir import Field, FrozenText, Import, Model
from pydantic_codegen.python_source import PythonSource, concatenated


class RecipeLabel(FrozenText): ...


def rendered_import(statement: Import) -> PythonSource:
    if statement.name is None:
        bare = f"import {statement.module.root}"
        return PythonSource(
            bare if statement.alias is None else f"{bare} as {statement.alias.root}"
        )
    if statement.alias is None:
        return PythonSource(
            f"from {statement.module.root} import {statement.name.root}"
        )
    return PythonSource(
        f"from {statement.module.root} import {statement.name.root} as {statement.alias.root}"
    )


def _rendered_field(field: Field) -> PythonSource:
    declaration = f"    {field.name.root}: {field.annotation.root}"
    if field.default is None:
        return PythonSource(declaration)
    return PythonSource(f"{declaration} = {field.default.root}")


def _rendered_model(model: Model) -> PythonSource:
    bases = Arr(model.bases).map(lambda base: base.name.root).to_list()
    header = PythonSource(
        f"class {model.name.root}({', '.join(bases)}):"
        if bases
        else f"class {model.name.root}:"
    )
    if not model.fields:
        return header.followed_by(PythonSource("    pass"))
    return concatenated(Arr([header]).chain(Arr(model.fields).map(_rendered_field)))


def imports_of(models: Arr[Model]) -> Arr[Import]:
    from_fields = (
        models.map(lambda model: model.fields)
        .flatten()
        .map(lambda field: field.imports)
        .flatten()
    )
    from_models = models.map(lambda model: model.imports).flatten()
    unique: list[Import] = from_models.chain(from_fields).unique().to_list()
    # Only determinism matters: ruff's isort pass reorders the block afterwards.
    by_module_and_name = {
        (
            statement.module.root,
            statement.name.root if statement.name else "",
            statement.alias.root if statement.alias else "",
        ): statement
        for statement in unique
    }
    return Arr([by_module_and_name[key] for key in sorted(by_module_and_name)])


def rendered(models: Arr[Model], recipe: RecipeLabel) -> PythonSource:
    header = Arr(
        [
            PythonSource("# Generated by pydantic-codegen. Do not edit."),
            PythonSource(f"# Recipe: {recipe.root}"),
        ]
    )
    imports = imports_of(models).map(rendered_import)
    classes = models.map(_rendered_model)
    return concatenated(header.chain(imports).chain(classes)).followed_by(
        PythonSource("")
    )
