from iterpy import Arr

from pydantic_codegen.ir import (
    AnnotationText,
    BaseName,
    DefaultText,
    Field,
    FieldName,
    Import,
    Model,
    ModelName,
    ModuleName,
    SymbolName,
)
from pydantic_codegen.python_source import PythonSource
from pydantic_codegen.renderer import RecipeLabel, rendered


def test_renders_header_imports_and_class() -> None:
    model = Model(
        name=ModelName("CreateSubfolderPayload"),
        bases=(BaseName("FlowbasePayloadModel"),),
        fields=(
            Field(
                name=FieldName("name"),
                annotation=AnnotationText("SubfolderName"),
                imports=(
                    Import(
                        module=ModuleName("domain.subfolder"),
                        name=SymbolName("SubfolderName"),
                    ),
                ),
            ),
        ),
        imports=(
            Import(
                module=ModuleName("djank.services.base"),
                name=SymbolName("FlowbasePayloadModel"),
            ),
        ),
    )

    assert rendered(Arr([model]), RecipeLabel("/djank/codegen.py")) == PythonSource(
        "# Generated by pydantic-codegen. Do not edit.\n"
        "# Recipe: /djank/codegen.py\n"
        "from djank.services.base import FlowbasePayloadModel\n"
        "from domain.subfolder import SubfolderName\n"
        "class CreateSubfolderPayload(FlowbasePayloadModel):\n"
        "    name: SubfolderName\n"
    )


def test_renders_default_and_import_forms() -> None:
    model = Model(
        name=ModelName("Tagged"),
        fields=(
            Field(
                name=FieldName("created"),
                annotation=AnnotationText("datetime.datetime"),
                default=DefaultText("Field(default_factory=list)"),
                imports=(
                    Import(module=ModuleName("datetime")),
                    Import(
                        module=ModuleName("pydantic"),
                        name=SymbolName("Field"),
                        alias=SymbolName("F"),
                    ),
                ),
            ),
        ),
    )

    assert rendered(Arr([model]), RecipeLabel("/codegen.py")) == PythonSource(
        "# Generated by pydantic-codegen. Do not edit.\n"
        "# Recipe: /codegen.py\n"
        "import datetime\n"
        "from pydantic import Field as F\n"
        "class Tagged:\n"
        "    created: datetime.datetime = Field(default_factory=list)\n"
    )


def test_model_without_fields_emits_pass() -> None:
    model = Model(name=ModelName("Empty"))

    assert rendered(Arr([model]), RecipeLabel("/codegen.py")) == PythonSource(
        "# Generated by pydantic-codegen. Do not edit.\n"
        "# Recipe: /codegen.py\n"
        "class Empty:\n"
        "    pass\n"
    )


def test_renders_an_aliased_module_import() -> None:
    model = Model(
        name=ModelName("Stamped"),
        fields=(
            Field(
                name=FieldName("created"),
                annotation=AnnotationText("dt.datetime"),
                imports=(
                    Import(module=ModuleName("datetime"), alias=SymbolName("dt")),
                ),
            ),
        ),
    )

    assert rendered(Arr([model]), RecipeLabel("/codegen.py")) == PythonSource(
        "# Generated by pydantic-codegen. Do not edit.\n"
        "# Recipe: /codegen.py\n"
        "import datetime as dt\n"
        "class Stamped:\n"
        "    created: dt.datetime\n"
    )
